### ISSUE TITLE
rename repo to terraform-provider-kubernetes-yaml

### ISSUE THREAD

**Issue by jhoblitt** [lawrencegripper/terraform-provider-kubernetes-yaml#1]
This repo can't currently be built when cloned without specifying a explicit destination dir name as the expected name is

github.com/lawrencegripper/terraform-provider-kubernetes-yaml

instead of

github.com/lawrencegripper/terraform-kubernetes-yaml

**Comment by lawrencegripper** [comment]
Wow your quick - thanks for the heads up - expect a bit of churn for the next few hours as I'm getting everything setup. 

If all goes well I'll auto publish builds to the releases page.

**Comment by jhoblitt** [comment]
@lawrencegripper I appreciate the effort your putting into this.  I have never used, as it was abandoned before I discovered it, but I am aware of a previous attempt along the same lines: https://github.com/ericchiang/terraform-provider-k8s/

It might also be worth changing the default gh repo branch to be that of a dev branch or replacing the master branch completely since this is essentially a perma-fork.

**Comment by lawrencegripper** [comment]
thanks, yeah the existing examples which I've seen all use invoke [`kubectl` under the covers](https://github.com/ericchiang/terraform-provider-k8s/blob/master/main.go#L123). This creates problems if you're TF is working with multiple clusters at the same time. 

Hopefully this approach, using the kubernetes API directly, is more reliable but need some more testing to prove that out. 

Master is now up-to-date with the changes from the [PR](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/195) and some additional changes (renaming the provider `k8sraw`). Once the build completes should be all good for some testing. 

I've updated the [`_examples`](https://github.com/lawrencegripper/terraform-provider-kubernetes-yaml/blob/master/_examples/yaml/main.tf) folder and the [`Readme.md`](https://github.com/lawrencegripper/terraform-provider-kubernetes-yaml#using-the-provider) so if you have a change to have a play and let me know how you get on that would be awesome.

**Comment by jhoblitt** [comment]
@lawrencegripper I've given it a try and run into a problem with refresh blowing up (haven't tried to debug yet) but resource creation is working: #8.  I suppose we should close this ticket since it has been implemented?
