### ISSUE TITLE
Release binaries are not statically linked

### ISSUE THREAD

**Issue by stepanstipl** [lawrencegripper/terraform-provider-kubernetes-yaml#16]
Binaries published as "Releases" on Github are not statically linked, and therefore fail running on `Alpine`.

### Expected Behavior

```console
$ ./terraform-provider-k8sraw-linux-amd64
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

### Actual Behavior

```console
$ ./terraform-provider-k8sraw-v0.1.45
Error relocating ./terraform-provider-k8sraw-v0.1.45: __vfprintf_chk: symbol not found
Error relocating ./terraform-provider-k8sraw-v0.1.45: __fprintf_chk: symbol not found
```

### Steps to Reproduce

```console
$ ldd terraform-provider-k8sraw-v0.1.45
        /lib64/ld-linux-x86-64.so.2 (0x7f540094e000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f540094e000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f540094e000)
Error relocating terraform-provider-k8sraw-v0.1.45: __vfprintf_chk: symbol not found
Error relocating terraform-provider-k8sraw-v0.1.45: __fprintf_chk: symbol not found
```

### Important Factoids

The problem seems to be in the build script, where `CGO_ENABLED=0` is not "exported" and therefore not available to the go subprocess (nor is it propagated via putting it in front of the build command).

**Comment by lawrencegripper** [comment]
Sorry this one slipped through my notifications. 

Thanks for raising the issue with all the details and the PR - really appreciated. (Also sorry about the bug in the build script)
