### ISSUE TITLE
binary releases

### ISSUE THREAD

**Issue by jhoblitt** [lawrencegripper/terraform-provider-kubernetes-yaml#6]
Binary releases make automating the install of "out-of-tree" providers a bit easier.

**Comment by lawrencegripper** [comment]
Agreed, got it all ready to go but missed a `skip_cleanup: true` in my travis config - hopefully the next build should output binaries for all platforms.

**Comment by lawrencegripper** [comment]
Builds on `master` now produce binary outputs in [releases](https://github.com/lawrencegripper/terraform-provider-kubernetes-yaml/releases)
