### ISSUE TITLE
Provider depends_on another resource

### ISSUE THREAD

**Issue by ydewit** [lawrencegripper/terraform-provider-kubernetes-yaml#9]
We would like to provision the k8s cluster created within the same terraform execution (and same state file). 

I see that this is a long standing issue: see https://github.com/hashicorp/terraform/issues/2430.

Could we work around this terraform limitation by using the provider as a holder of configuration attributes only, and instantiate the k8s client lazily?

**Comment by lawrencegripper** [comment]
I think this is possible with the current provider setup. You can initialize a provider with the output of the cluster creation and then use that to configure the resulting cluster. I have an example of this working for Azure AKS clusters here: https://github.com/lawrencegripper/azure-aks-terraform/blob/master/main.tf#L83

```hcl

provider "kubernetes" {
  host = "${azurerm_kubernetes_cluster.aks.kube_config.0.host}"

  client_certificate     = "${base64decode(azurerm_kubernetes_cluster.aks.kube_config.0.client_certificate)}"
  client_key             = "${base64decode(azurerm_kubernetes_cluster.aks.kube_config.0.client_key)}"
  cluster_ca_certificate = "${base64decode(azurerm_kubernetes_cluster.aks.kube_config.0.cluster_ca_certificate)}"
}

resource "kubernetes_secret" "redis_secret" {
  metadata {
    name = "rediskeys"
  }

  data {
    host = "${azurerm_redis_cache.redis.hostname}"
    port = "${azurerm_redis_cache.redis.port}"
    key  = "${azurerm_redis_cache.redis.primary_access_key}"
  }
}
```

**Comment by ydewit** [comment]
@lawrencegripper Thanks for the pointer here. Indeed that solves this problem for me.

I am still struggling with setting up the provider for AWS since it requires the use of the aws-iam-authenticator, which means I need to generate the kubeconfig locally and hope it is not deleted (local_file doesn't seem to regenerate the file if it is deleted).

**Comment by sppwf** [comment]
@ydewit 
use next config
```hcl
module "eks" {
  --- code for eks module with proper output ---
}

data "aws_eks_cluster_auth" "this" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster" "this" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.this.token
  load_config_file       = false
}
```

**Comment by kadzu** [comment]
Don't make sense... creating a configuration on IaC and can't be update!..

Instead, I used local-exec and sh script with ENV vars.. (workaround)
